reddit-bq-dbt:
  outputs:
    dev:
      dataset: reddit_dataset
      fixed_retries: 1
      keyfile: /home/src/keys/de-reddit-reports-f9479aba34a3.json
      location: northamerica-northeast1
      method: service-account
      priority: interactive
      project: de-reddit-reports
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev