version: '3'
services:
  magic:
    # image: mageai/mageai:latest
    image: mageai_with_gcloud_sdk_dbt:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      REDDIT_APP_NAME: ${REDDIT_APP_NAME}
      REDDIT_APP_ID: ${REDDIT_APP_ID}
      REDDIT_SECRET: ${REDDIT_SECRET}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    # restart: on-failure:5
