version: 2

sources:
    - name: staging
      database: de-reddit-reports
      schema: reddit_dataset

      tables:
        - name: dataengineering_staging

models:
  - name: reddit_data_consolidated
    columns:
      - name: post_id
      - name: comment_id
    unique:
      - [post_id, comment_id]